spring:
  datasource:
    url: jdbc:h2:mem:testdb

#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: http://localhost:8083/auth/realms/baeldung
#          jwk-set-uri: http://localhost:8083/auth/realms/baeldung/protocol/openid-connect/certs

  h2:
    console:
      enabled: true


#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=password
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect